/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.26
 * Generated at: 2017-10-03 01:14:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.masterMenu;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("f:url", org.seasar.struts.taglib.S2Functions.class, "url", new Class[] {java.lang.String.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/view/common/common.jsp", Long.valueOf(1506910846981L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; UTF-8;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css\">\r\n");
      out.write("<style>\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("$(function() {\r\n");
      out.write("\t// 1.ボタン1が押されたときの動作\r\n");
      out.write("\t$(\"#id1\").click(function() {\r\n");
      out.write("\t\t$(\"#profile\").dialog({\r\n");
      out.write("\t\t\tmodal:true, //モーダル表示\r\n");
      out.write("\t\t\theight: 260,\r\n");
      out.write("\t\t\twidth: 550,\r\n");
      out.write("\t\t\ttitle:\"プロフィール情報\", //タイトル\r\n");
      out.write("\t\t\tbuttons: { //ボタン\r\n");
      out.write("\t\t\t\"確認\": function() {\r\n");
      out.write("\t\t\t\t$(this).dialog(\"close\");\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\"キャンセル\": function() {\r\n");
      out.write("\t\t\t\t$(this).dialog(\"close\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${f:url('/css/mastermenu.css')}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0, false));
      out.write("\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${f:url('/css/lightbox.css')}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0, false));
      out.write("\">\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${f:url('/js/lightbox.min.js')}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0, false));
      out.write("\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>カラオケBonBon管理システム</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"pagebody\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- ヘッダ -->\r\n");
      out.write("\t<div id=\"header\"><h1><a href=\"index.jsp\">カラオケBonBonマスタ管理</a></h1></div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- サブメニュー（左カラム） -->\r\n");
      out.write("\t<div id=\"submenu\">\r\n");
      out.write("\t\t<!-- <font siza=\"1\" align=\"left\">従業員CD:TEST000001</font><br>\r\n");
      out.write("\t\t<font siza=\"1\" align=\"left\">従業員名:テスト 太郎</font> -->\r\n");
      out.write("\t\t<p align=\"left\">従業員CD:TEST000001</p>\r\n");
      out.write("\t\t<p align=\"left\">従業員名:テスト 太郎</p>\r\n");
      out.write("\t\t<div id=\"submenu_header\">従業員情報管理</div>\r\n");
      out.write("\t\t<ul id=\"submenu_body\">\r\n");
      out.write("\t\t\t<div id=\"profile\" style=\"display:none;\">\r\n");
      out.write("\t\t\t<table class=\"type11\">\r\n");
      out.write("\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th scope=\"cols\">従業員CD</th>\r\n");
      out.write("\t\t\t\t\t<th scope=\"cols\">名前</th>\r\n");
      out.write("\t\t\t\t\t<th scope=\"cols\">電話番号</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>TEST000001</th>\r\n");
      out.write("\t\t\t\t\t<td>テスト 太郎</th>\r\n");
      out.write("\t\t\t\t\t<td>09012345678</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"display:inline-flex\" align=\"center\">\r\n");
      out.write("\t\t\t<input type=\"button\" id=\"id1\" value=\"アドミン情報\" />\r\n");
      out.write("\t\t\t<input type=\"button\"  value=\"ログアウト\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</ul><br>\r\n");
      out.write("\r\n");
      out.write("\t\t<div Align=\"left\">\r\n");
      out.write("\t\t\t<a href=\"i");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${f:url('/images/office.gif')}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0, false));
      out.write("\" data-lightbox=\"オフィス\"><img src=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${f:url('/images/office.gif')}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0, false));
      out.write(" width=\"300\" height=\"320\"/></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- コンテンツ（中央と右の2カラム） -->\r\n");
      out.write("\t<div id=\"content\">\r\n");
      out.write("\t\t<!-- ニュース（中央カラム） -->\r\n");
      out.write("\t\t<div id=\"news\">\r\n");
      out.write("\t\t\t<div Align=\"center\">\r\n");
      out.write("\t\t\t<h2>MENU一覧</h2>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"nav\" align=\"center\">\r\n");
      out.write("\t\t\t\t<ul class=\"nl\">\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">・社員登録</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">・店舗登録</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">・社員検索</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">・店舗検索</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- フッタ -->\r\n");
      out.write("\t<div id=\"footer\"><address>Copyright (c) SA CONSULTING All Rights Reserved.</address></div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
